### ISSUE TITLE
Regarding point (5)

### ISSUE THREAD

**Issue by thanosbcc** [EAddario/java-master#1]
@EAddario is point (5) on CONTRIBUTING.md, especially the term 'indefinitely', contradictory to GDPR, in the sense that at any point a user should be able to retrieve and ask for all their data to be removed from our platform?
I may be misinterpreting the whole sentence but I thought of asking.

**Comment by EAddario** [comment]
Very shrewd observation thanosbcc, and precisely because GDPR and other similar data privacy regulations, #5 becomes critical for contributors to known and accept. Any and all contributions are ultimately handled via GitHub and we have no way to control who and how that information is stored and/or accessed.
